import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink, RouterLinkActive, RouterModule } from '@angular/router';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

import {
  LucideAngularModule,
  Home,
  Package,
  Users,
  LineChart,
  Settings,
  Bell,
  Search,
  Menu,
  User,
  LogOut,
  LayoutDashboard,
  Truck,
  MapPin,
  CreditCard,
  HelpCircle,
  Shield,
  Mail,
  Phone,
  Calendar,
  DollarSign,
  Box,
  FileText,
  Shirt,
  Laptop,
  Package2,
  ShoppingCart,
  CircleUser,
  PlusCircle,
  Activity,
  ArrowUpRight,
  ChevronDown,
  Circle,
  DollarSignIcon,
  ExternalLink,
  IndianRupee,
  MoreVertical,
  PackagePlus,
  PackageSearch,
  PanelLeft,
  Plus,
  Settings2,
  ShoppingCartIcon,
  Upload,
  Wallet,
  XCircle,
  ChevronLeft,
  ChevronRight,
} from 'lucide-angular';
import { IconModule } from './components/icon/icon.module';

const lucideIcons = {
  Home,
  Package,
  Users,
  LineChart,
  Settings,
  Bell,
  Search,
  Menu,
  User,
  LogOut,
  LayoutDashboard,
  Truck,
  MapPin,
  CreditCard,
  HelpCircle,
  Shield,
  Mail,
  Phone,
  Calendar,
  DollarSign,
  Box,
  FileText,
  Shirt,
  Laptop,
  Package2,
  ShoppingCart,
  CircleUser,
  PlusCircle,
  Activity,
  ArrowUpRight,
  ChevronDown,
  Circle,
  DollarSignIcon,
  ExternalLink,
  IndianRupee,
  MoreVertical,
  PackagePlus,
  PackageSearch,
  PanelLeft,
  Plus,
  Settings2,
  ShoppingCartIcon,
  Upload,
  Wallet,
  XCircle,
  ChevronLeft,
  ChevronRight,
};

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    RouterModule,
    IconModule,
  ],
  exports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    RouterModule,
    IconModule,
    RouterLink,
    RouterLinkActive,
  ],
})
export class SharedModule {}
